elasticsearch-masters:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "logs"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        discovery.zen.ping.unicast.hosts: '["es-masters"]'
elasticsearch-datanodes:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "logs"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        discovery.zen.ping.unicast.hosts: '["es-masters"]'
elasticsearch-clients:
  metadata:
    elasticsearch:
      yml:
       cluster.name: "logs"
       node.name: "$${HOSTNAME}"
       node.data: "false"
       node.master: "false"
       discovery.zen.ping.unicast.hosts: '["es-masters"]'
